server:
  port: 9001

spring:
  application:
    name: user-service

  datasource:
    name: MyDB1
    url: jdbc:mysql://localhost:3306/micro_api
    username: root
    password: Admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQLDialect
   hibernate:
     ddl-auto: update

eureka:
  instance:
    hostname: localhost





